### ISSUE TITLE
Error when creating new project

### ISSUE THREAD

**Issue by cdarken** [ETCDEVTeam/emerald#26]
When I run `emerald new` I get this error:

```
⠙ Creating new project/usr/local/lib/node_modules/emerald/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filen

Error: EXDEV: cross-device link not permitted, rename '/var/www/learn/cryptocurr/emerald-app/1542180924926-10244903732153965/emerald-starter-kit-master' -> '/tmp/tmp-24584mW2r3ut651dM'
```

**Comment by shanejonas** [comment]
Hi, this is an issue with using the `rename` command across partitions.

theres a workaround for this right now from here #9 

```
export TMP=~/tmp; npm install -g https://github.com/ETCDEVTeam/emerald.git
```

**Comment by cdarken** [comment]
I'm not trying to install emerald, that works just fine. The issue is when trying to generate new project.

**Comment by phyro** [comment]
There is a NOTE added at the end:
```
NOTE: for anyone having this issue, unless you put this in your .bashrc or equivalent, you'll have to run export TMP=/home/phyro/tmp before using some of the commands eg. emerald new
```
is your `/var/...` in the same partition as `~/`? If it is, you can try what Shane said so creating an empty folder `~/tmp`  and then doing `export TMP=~/tmp;` inside the terminal (if it is not, you need to set TMP var to some folder on the same partition otherwise you will probably still get the cross-device error) where you want to run `emerald new` and see if you still get the error.
If this doesn't help, then perhaps installing with the whole command that Shane pasted and after install is completed doing `export TMP=~/tmp; emerald new`

If it does work, then you will need to do `export TMP=..` every time you open a new terminal unless you automate this eg. putting the export in .bashrc or whatever equivalent you have

**Comment by cdarken** [comment]
Thanks for the help, I got it now, I set TMP to a dir in /var/www because even if it's on the same physical partition it's mounted with bind on /var/www and I guess that's why it gets confused.
